tasks:
  default:
    onboard_world: MessengerBotChatOnboardWorld
    task_world: MessengerBotChatTaskWorld
    timeout: 1800
    agents_required: 1
task_name: chatbot
world_module: parlai.chat_service.tasks.chatbot.world.wikiworld
overworld: MessengerOverworld
max_workers: 30
opt:
  debug: True
  models:
    dodecadialogue:
      model: image_seq2seq
      model_file: zoo:dodecadialogue/wizard_of_wikipedia_ft/model
      interactive_mode: True
      no_cuda: False
additional_args:
  page_id: 1 # Configure Your Own Page
